INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('1','(이신현 장편소설)공존의 그늘 5','이신현 지음','(도서출판)다나','19050615');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('3','공무원, 우리는 아무말도 하지 않았다','최민호 지음','박영률출판사','19050622');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('4','(막노동꾼 출신 서울대 수석합격자 장승수 이야기) 공부가 가장 쉬웠어요','장승수 지음','김영사','19050618');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('6','공룡 계곡의 비밀','브레지나 토마스 지음','(주)사계절출판사','19050617');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('7','궁합.3','강영수 지음','한아름','19050617');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('8','그들의 오후','윤정모 지음','창작과 비평사','19050620');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('9','(그라운드)제로','케빈 J. 앤더슨 지음','(주)시공사','19050619');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('10','그때 말이있었네','최일남 지음','나남','19050612');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('11','그때 그 도마뱀은 무슨 표정을 지었을까','도종환 지음','(주)사계절출판사','19050620');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('12','그들은 어떻게 유명해졌을까','권성희 지음','(도서출판)맑은소리','19050624');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('13','그들은 어디서 만날까!','앤 타일러 지음','은하','19050616');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('14','그대 하늘에 달로 뜨리라','김초혜 지음','문학세계사','19050610');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('15','그대 이름으로 흔들릴 때','김현숙 지음','인문당','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('16','그를 버린 여인. 하','이병주  저','서 당','19050612');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('17','(그러니까)당신도 살아','오히라 미쓰요 지음','북하우스','19050622');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('18','그래도 나는 가볍게 살고 싶다','이주향 지음','청년사','19050620');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('19','그래도 꿈꾸어야 하리','헤르만 헤세 지음','타임기획','19050612');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('20','그래 그래, 좋아 좋아','최래옥 지음','제삼기획','19050621');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('21','(아름다운 세상 사랑하는 사람들)그래그래','이은경 지음','亨宣(형선)','19050617');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('22','그는 언제 오는가','신경숙 외 지음','조선일보사','19050619');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('23','그래, 넌 박사를 잡아 난 세상을 잡을 거야','문인석 지음','서울문화사','19050622');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('24','47 그들이 온다','철도해고자원직복직투쟁위원회 지음','갈무리','19050629');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('25','그래, 수다로 풀자','오숙희 지음','석필','19050616');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('27','그래서 그들은 바다로 갔다 1','그리샴 존 지음','시공사','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('29','그래서 그들은 바다로 갔다 2','그리샴 존 지음','시공사','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('31','(김창동 장편소설)그래도 우리는 사랑한다','김창동 지음','반도기획','19050615');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('32','그래도 물고기는 물에서 논다','권용철 지음','화랑출판사','19050615');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('33','그래도 내가 할 수 있는 말은','벅맨 로버트 지음','미래향문화','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('34','기계 상','벨레토 르네 지음','열린책들','19050617');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('36','기계 하','벨레토 르네 지음','열린책들','19050617');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('38','(하진장편소설)기다림','하진 지음','시공사','19050629');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('39','Give보단 take가 더 효과적이래','조하경 지음','가원','19050618');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('40','기자,똑바로 해야지!','고승우 지음','춘추원','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('41','기적','월레스 어빙 지음','청목','19050608');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('42','기적의 인간','심포 유이치 지음','들녘','19050619');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('43','고슴도치를 사랑한 카멜레온','모라비아 알베르토 지음','언어문화','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('45','김대중, 희망을 위한 여정','김홍균 지음;','고즈윈','19050628');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('46','그들은 한 권의 책에서 시작되었다','정혜윤 지음','푸른숲','19050630');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('51','그림 상식 백과','김춘수 엮음','宇石(우석)','19050616');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('52','금지된 사람들','염승호 지음','남도','19050619');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('53','그 많은 느림은 다 어디로 갔을까','장석주 지음','뿌리와이파리','19050630');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('54','금삼의 피','박종화 지음','범우사','19050606');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('55','(사랑의테마 장편 옴니버스 소설시리즈 2) 비련초','경요 지음','홍익출판사','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('56','(사랑의 테마 장편 옴니버스 소설시리즈 2) 비련초','경요 지음','홍익출판사','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('57','(사랑의 테마 장편 옴니버스 소설시리즈 3) 은잔화','경요 지음','홍익출판사','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('58','(사랑의 테마 장편 옴니버스 소설시리즈 4) 행운초','경요 지음','홍익출판사','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('59','(사랑의 테마 장편 옴니버스 소설시리즈 5) 유리꽃','경요 지음','홍익출판사','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('60','(사랑의 테마 장편 옴니버스 소설시리즈 1) 금잔화','경요 지음','홍익출판사','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('65','(만화)기독교 강요','존 칼빈 원작','생명의 말씀사','19050702');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('66','예술의 종말 이후','아서 단토 지음','미술문화','19050702');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('67','한국대표 단편소설; 사랑 손님과 어머니 외 10편 수록','주요섭 외 지음','지경사','19050628');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('68','사람이 좋다 삼수가 좋다','장영진 지음','맑고깊고넓은물','19050701');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('73','여자, 그림으로 행복해지다','남인숙 지음','소담출판사','19050702');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('78','경산 신아리랑','신재기 지음','도서출판 학이사','19050702');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('82','고산자','박범신 지음','문학동네','19050701');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('85','그건, 사랑이었네','한비야 지음','(주)도서출판 푸른숲','19050701');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('87','기묘한 신혼여행','히가시노 게이고 등 지음','문학의문학','19050630');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('89','길따라 숲찾아','김봉규 지음','노벨미디어','19050630');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('90','그 화사한 미소속에','프레데릭 포사이스 외 지음','덕성문화사','19050611');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('92','(완결편)금병매; 제1권 환생','몽필생 지음','열사람','19050615');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('93','(완결편)금병매; 제2권 욕망','몽필생 지음','열사람','19050615');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('94','(완결편)금병매; 제3권 업보','몽필생 지음','열사람','19050615');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('95','(제1권 색남색녀) 금병매','하근찬 지음','고려원','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('97','(제2권 여자사냥) 금병매','하근찬 지음','고려원','19050614');
INSERT INTO book (bno,btitle,bwriter,bpublisher,bpu_date) VALUES ('98','(제3권 사랑과 증오) 금병매','하근찬 지음','고려원','19050614');